development:
  adapter: postgresql
  encoding: unicode
  database: botlist_development
  pool: 5
  username: botlist
  password: botlist
  host: 127.0.0.1
  port: 5434

test: &test
  adapter: postgresql
  encoding: unicode
  database: botlist_test
  pool: 5
  username: botlist
  password: botlist
  host: 127.0.0.1
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: botlist_production
  pool: 5
  username: botlist
  password: botlist
  host: 127.0.0.1
  port: 5432